# Generated by Django 5.2.3 on 2025-11-21 03:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('CS', 'Cessna Aircraft'), ('PA', 'Piper Aircraft'), ('BC', 'Beechcraft Aircraft'), ('BD', 'Bombardier'), ('DH', 'Daher'), ('DS', 'Dassault Aviation'), ('EB', 'Embraer'), ('GS', 'Gulfstream Aerospace'), ('PL', 'Pilatus Aircraft'), ('TX', 'Textron Aviation'), ('OT', 'Other')], default='OT', max_length=2)),
                ('aircraft_type', models.CharField(choices=[('ST', 'Single Engine Turboprop'), ('TT', 'Twin Engine Turboprop'), ('SJ', 'Single Engine Jet'), ('TJ', 'Twin Engine Jet'), ('JJ', 'Three Engine Jet'), ('OT', 'Other')], default='OT', max_length=2)),
                ('model', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('registration', models.CharField(max_length=50)),
                ('total_time', models.DecimalField(decimal_places=1, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500000)])),
                ('total_cycles', models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('manufacturer', 'model', 'serial', 'registration'), name='unique_aircraft')],
            },
        ),
        migrations.CreateModel(
            name='AircraftFlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateTimeField(verbose_name='Flight Date')),
                ('flight_hours', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Flight Hours')),
                ('press_altitude', models.IntegerField(help_text='Pressure Altitude in feet', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70000)], verbose_name='Pressure Altitude')),
                ('outside_air_temp', models.DecimalField(decimal_places=1, help_text='OAT in degrees Celsius', max_digits=3, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Outside Air Temperature')),
                ('indicated_air_speed', models.IntegerField(blank=True, help_text='IAS in knots', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Indicated Air Speed')),
                ('mach_number', models.DecimalField(blank=True, decimal_places=1, help_text='Mach Number', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Mach Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_records', to='aircraft.aircraft', verbose_name='Aircraft')),
            ],
            options={
                'verbose_name': 'Aircraft Flight Record',
                'verbose_name_plural': 'Aircraft Flight Records',
                'ordering': ['-flight_date'],
            },
        ),
    ]
