# Generated by Django 5.2.3 on 2025-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_alter_aircraft_registration_alter_aircraft_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('ST', 'Single Engine Turboprop'), ('TT', 'Twin Engine Turboprop'), ('SJ', 'Single Engine Jet'), ('TJ', 'Twin Engine Jet'), ('JJ', 'Three Engine Jet'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.CharField(help_text='Example: King Air 350', max_length=255),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='serial',
            field=models.CharField(max_length=255, verbose_name='S/N'),
        ),
    ]
