# Generated by Django 5.2.3 on 2025-12-10 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_alter_aircraft_aircraft_type_alter_aircraft_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField(help_text='Flight date')),
                ('flight_hours', models.DecimalField(decimal_places=1, default=0, help_text='Example: 2.5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='aircraft.aircraft', verbose_name='Aircraft')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['-flight_date'],
            },
        ),
        migrations.CreateModel(
            name='FlightEngineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_altitude', models.IntegerField(help_text='Example: 27500', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70000)], verbose_name='Cruise Pressure Altitude (feet)')),
                ('outside_air_temp', models.DecimalField(decimal_places=1, help_text='Example: -38.5', max_digits=3, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Cruise OAT (°C)')),
                ('indicated_air_speed', models.IntegerField(blank=True, help_text='Example: 320', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Cruise IAS (knots)')),
                ('mach_number', models.DecimalField(blank=True, decimal_places=1, help_text='Example: 0.85', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Cruise Mach Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_data', to='aircraft.flight', verbose_name='Flight')),
            ],
            options={
                'verbose_name': 'Flight Engine Data',
                'verbose_name_plural': 'Flight Engine Data',
                'ordering': ['-flight__flight_date'],
            },
        ),
        migrations.DeleteModel(
            name='AircraftFlightRecord',
        ),
    ]
