# Generated by Django 5.2.6 on 2025-09-20 23:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, choices=[('hw', 'Honeywell'), ('rr', 'Rolls-Royce'), ('ge', 'General Electric'), ('pw', 'Pratt & Whitney'), ('wl', 'Williams'), ('ot', 'Other')], default='', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('tr', 'Turbojet'), ('tf', 'Turbofan'), ('tp', 'Turboprop'), ('ts', 'Turboshaft'), ('ot', 'Other')], default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('time_since_new', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('999999.9'))], verbose_name='TSN (hours)')),
                ('cycles_since_new', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='CSN (cycles)')),
                ('time_since_overhaul', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('99999.9'))], verbose_name='TSO (hours)')),
                ('cycles_since_overhaul', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='CSO (cycles)')),
                ('time_between_overhauls', models.DecimalField(decimal_places=1, default=Decimal('3500.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9999.9'))], verbose_name='TBO (hours)')),
            ],
        ),
    ]
