# Generated by Django 5.2.3 on 2025-12-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='type',
            new_name='engine_type',
        ),
    ]
