# Generated by Django 5.2.3 on 2025-12-10 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0004_flight_flightenginedata_delete_aircraftflightrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FBO', 'FBO'), ('FUEL', 'Fuel'), ('HOTEL', 'Hotel'), ('MAINTENANCE', 'Maintenance'), ('MEAL', 'Meal'), ('PARKING', 'Parking'), ('TAXI', 'Taxi'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('TRANSFER', 'Transfer'), ('ZELLE', 'Zelle'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('expense_amount', models.DecimalField(decimal_places=2, help_text='Example: 1200.50', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Expense Amount (USD)')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='aircraft.flight', verbose_name='Flight')),
            ],
            options={
                'verbose_name': 'Flight Expense',
                'verbose_name_plural': 'Flight Expenses',
                'ordering': ['-flight__flight_date'],
            },
        ),
    ]
