# Generated by Django 5.2.3 on 2025-12-17 03:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_rename_flight_hours_flight_hours_flown_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('JET_A', 'Jet A'), ('JET_A1', 'Jet A-1'), ('JET_B', 'Jet B'), ('AVGAS', 'Avgas')], default='JET_A1', max_length=20, verbose_name='Type')),
                ('fuel_units', models.CharField(choices=[('L', 'Liters'), ('GAL', 'Gallons'), ('KG', 'Kilograms'), ('LB', 'Pounds')], default='L', max_length=20, verbose_name='Units')),
                ('fuel_quantity', models.DecimalField(decimal_places=1, default=0.0, help_text='No units, just the quantity. Example: 1200.5', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Quantity')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Example: 960.75', max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Amount Paid (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_paid', to='aircraft.flight', verbose_name='Flight')),
            ],
            options={
                'verbose_name': 'Fuel Paid',
                'verbose_name_plural': 'Fuel Paid',
                'ordering': ['-flight__flight_date'],
            },
        ),
    ]
