# Generated by Django 5.2.3 on 2025-11-21 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='registration',
            field=models.CharField(help_text='Example: N123456', max_length=50),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='serial',
            field=models.CharField(max_length=255, verbose_name='Aircraft S/N'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_cycles',
            field=models.IntegerField(default=0, help_text='Example: 1200', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Total Cycles'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_time',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Example: 2500.5', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500000)], verbose_name='Total Time (hours)'),
        ),
        migrations.AlterField(
            model_name='aircraftflightrecord',
            name='flight_date',
            field=models.DateField(help_text='Flight date'),
        ),
        migrations.AlterField(
            model_name='aircraftflightrecord',
            name='flight_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Example: 2.5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='aircraftflightrecord',
            name='indicated_air_speed',
            field=models.IntegerField(blank=True, help_text='Example: 320', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Cruise IAS (knots)'),
        ),
        migrations.AlterField(
            model_name='aircraftflightrecord',
            name='mach_number',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Example: 0.85', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Cruise Mach Number'),
        ),
        migrations.AlterField(
            model_name='aircraftflightrecord',
            name='outside_air_temp',
            field=models.DecimalField(decimal_places=1, help_text='Example: -38.5', max_digits=3, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Cruise OAT (°C)'),
        ),
        migrations.AlterField(
            model_name='aircraftflightrecord',
            name='press_altitude',
            field=models.IntegerField(help_text='Example: 27500', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70000)], verbose_name='Cruise Pressure Altitude (feet)'),
        ),
    ]
