# Generated by Django 5.2.3 on 2025-12-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_flight_flightenginedata_delete_aircraftflightrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_hours',
            new_name='hours_flown',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.CharField(default=None, help_text='For example: LFPG', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(default=None, help_text='For example: KJFK', max_length=4),
            preserve_default=False,
        ),
    ]
