# Generated by Django 5.2.3 on 2025-12-17 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_rename_flight_hours_flight_hours_flown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='total_cycles',
            field=models.IntegerField(default=0, help_text='Total Accumulated Cycles. Example: 1200', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='TAC'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_time',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total Time Airframe. Example: 2500.5', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500000)], verbose_name='TTAF (hours)'),
        ),
    ]
