# Generated by Django 5.2.3 on 2025-12-27 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0006_alter_aircraft_total_cycles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='fuel_flow_unit',
            field=models.CharField(choices=[('KPH', 'kg/h'), ('LPH', 'lb/h')], default='kgh', max_length=3, verbose_name='Fuel Flow Unit'),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='EngineFF',
            field=models.IntegerField(blank=True, help_text='Fuel Flow. Example: 1200.5', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='FF'),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='EnginePR',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Engine Pressure Ratio. Example: 1.53', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='EPR'),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='EngineVib',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: 0.56', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Engine Vibration'),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='InterstageTT',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Interstage Turbine Temperature. Example: 1090.5', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='ITT'),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='OilAdded',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='OilPress',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='OilTemp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='SpeedN1',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Low Pressure Compressor Speed. Example: 85.5', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='LPC Speed (%)'),
        ),
        migrations.AddField(
            model_name='flightenginedata',
            name='SpeedN2',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='High Pressure Compressor Speed. Example: 97.2', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='HPC Speed (%)'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_time',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total Time Airframe in Hours. Example: 2500.5', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500000)], verbose_name='TTAF'),
        ),
        migrations.AlterField(
            model_name='flightenginedata',
            name='outside_air_temp',
            field=models.DecimalField(decimal_places=1, help_text='Example: -38.5', max_digits=3, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Cruise OAT'),
        ),
    ]
